### ISSUE TITLE
Popup needs indicators for loading, waiting, etc.

### ISSUE THREAD

**Issue by estasney** [estasney/HostedExt#16]
1. Loading screen after login
2. Progress bar or other display that updates with each successful POST request to server.

**Comment by estasney** [comment]
@manji209 Anything you can add?

**Comment by manji209** [comment]
Great job Eric!  Looks good and looks like it works well.  I would have to
spend more time on it to be able to give any proper input.

I can touch up the UI and test a couple different progress bars on the
popup.  I have some time in the mornings this week to work on this.

Awesome work.

Dinh

**Comment by estasney** [comment]
Thanks @manji209!

You'll want to make sure you have newest master. I encountered several bugs especially around the token mechanisms.

I would greatly appreciate any UI support. I'm finding this challenging given that the popup will be frequently opened and closed and background.js must be able to track popup's state and be able to recreate it on demand. Complications arise when a session is interrupted. How do ensure previous session data does not make its way into a new one?

There has to be a more elegant solution to this problem but I'm not clear if there is a common design pattern for this in JavaScript.

I opened a new branch and wrote out some [TODOs](https://github.com/estasney/HostedExt/blob/5252d4359ade42ef57b5839301963059f4245aa3/ext/src/popup.js#L67-L71)

**Comment by manji209** [comment]
Thanks Eric,

Spent more time on it this morning.  Will do so again tomorrow morning.
Trying to test out some progress bars but I am still having problems
logging in with the credentials you supplied.  Could you send me the
credentials again in a separate email so it doesn't show in the comments
section.

Thanks,

dinh

**Comment by estasney** [comment]
@manji209 Emailed you with instructions on how to set up local server.

**Comment by estasney** [comment]
@manji209 Resuming work on this tomorrow. If you have any changes please push to a new branch. 

Thoughts on knockout? It appears ideal for this minus the non persistent popup.js

**Comment by estasney** [comment]
@manji209 Branch add-message-logging is my solution to solving mvc architecture.

Basically background.js continuously updates chrome.storage with key / values. Popup.js then renders view accordingly.

Currently it's a simple message log. Will map out several keys that popup.js can access for rendering ui

**Comment by estasney** [comment]
Add-logging-view

**Comment by estasney** [comment]
@manji209 add-logging-view now has these features. Will be merged with master once beta testing complete.
